# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
# Defines the pod for the Redis leader
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: redis
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend # helps identify to which part of the app the pod belongs

spec:
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels: # helps targeting the containers later
        app: redis
        role: leader
        tier: backend
    spec:
      containers:
        - name: leader
          image: "docker.io/redis:7.0.8"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
