# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook

apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-leader
  labels: # for categorization
    app: redis
    role: leader
    tier: backend

spec:
  ports:
  - port: 6379
    targetPort: 6379 # same as the container's port
  selector: # same as the container's labels
    app: redis
    role: leader
    tier: backend
