apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-practice-pv
  labels:
    td: pv

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
