apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  selector:
    app: nginx # targets the pods with this label
  ports:
  - name: http
    protocol: TCP
    port: 80 # port exposed by the containers inside the pod
  type: ClusterIP
